Yath
ledgersmb/LedgerSMB pull request #5364
Opened 2021-02-23 03:23 UTC by ylavoie

Move testing from `prove` to `yath (Test2-Harness)`, which allows a richer testing platform.

2021-02-23 14:29 UTC, ehuelsmann commented
I'm seeing that the screenshots are missing from the uploaded artifacts. Also, the lines in the html output suddenly have ”MATCH MODE” prepended.

2021-03-19 19:08 UTC, ehuelsmann requested changes
Overall, I like this change. I have two points I'd like to make:

1. I don't like the creation of the x2 directory  
    First of all, especially on CI infrastructure, the `89-dropdb.t` test doesn't add any value to the mix. Instead of moving it to a separate directory in order to prevent it from running: let's remove it all together.  
   Second of all, I don't like the fact that the `40-dbsetup.t` test needs to be specialized like this; instead of solving the creation as part of a test script, can't we (simply?) use the new `bin/ledgersmb-admin` script to create a valid database for our testing requirements?
2. Should a CI system really be using a persistent runner? Especially since there doesn't seem to be any pre-loading going on. Along the same lines: why did you choose 5 jobs? We are running this on CircleCI who provide us with two(?) VCPUs, meaning that 5 should be way more than we've been allocated.

2021-03-20 17:25 UTC, ylavoie commented
> 1. I don't like the creation of the x2 directory
>    First of all, especially on CI infrastructure, the `89-dropdb.t` test doesn't add any value to the mix. Instead of moving it to a separate directory in order to prevent it from running: let's remove it all together.

x2 is a standard test directory for `Test2` compatibles tests. Nevertheless, `40-dbsetup` & `89-dropdb` have now been replaced by `ledgersmb/admin` in another PR.

> 2. Should a CI system really be using a persistent runner? Especially since there doesn't seem to be any pre-loading going on. Along the same lines: why did you choose 5 jobs? We are running this on CircleCI who provide us with two(?) VCPUs, meaning that 5 should be way more than we've been allocated.

`yath` separated test parsing and execution so yes, sending all tests to a persistent runner allows to preload all execution dependencies only once. It does imply that we need to rely on yath job too, instead of only PID to allow tests running on a single database to run properly.

2021-03-20 18:59 UTC, ehuelsmann approved these changes

2021-03-20 19:00 UTC, merged