Jest components tests
ledgersmb/LedgerSMB pull request #7264
Opened 2023-03-12 06:11 UTC by ylavoie

This PR adds the basis for Jests for our UI and allow testing it independently from the server.
 
The infrastructure comprises:
- JSDOM to allow testing in a browserlike environment.
- A Mock Service Worker (MSW) to mock at network in order to fully test our components and code completely and without any changes.
- Mocks of the WebElements (lsmb-etxt, lsmb-password, ...) in order to free ourselves from Dojo & Dijit
 
Store tests and LoginPage as set first tests.

2023-03-12 21:05 UTC, ehuelsmann requested changes

2023-03-12 21:32 UTC, ylavoie commented on UI/src/views/LoginPage.vue
> +    setup(props, context) { // eslint-disable-line no-unused-vars
Neither props not context

2023-03-12 22:09 UTC, ylavoie commented on UI/src/views/LoginPage.vue
> +id="company"
Fixed

2023-03-12 22:09 UTC, ylavoie commented on UI/src/views/LoginPage.vue
> -                <div v-else style="background-color:red;border-radius:3px;padding:3px;font-weight:bold">{{ errorText }}</div>
Fixed

2023-03-12 22:09 UTC, ylavoie commented on UI/src/views/LoginPage.vue
> +    setup(props, context) { // eslint-disable-line no-unused-vars
Fixed

2023-03-13 06:07 UTC, ehuelsmann approved these changes
Thanks for the efforts.

2023-03-13 06:10 UTC, merged